function com_typeracer_guest_Guest(){var O='bootstrap',P='begin',Q='gwt.codesvr.com.typeracer.guest.Guest=',R='gwt.codesvr=',S='com.typeracer.guest.Guest',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='Chrome',gb='eval("',hb='");',ib='script',jb='javascript',kb='moduleStartup',lb='moduleRequested',mb='com_typeracer_guest_Guest',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='com.typeracer.guest.Guest::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='com.typeracer.guest.Guest.nocache.js',Ib='base',Jb='//',Kb='chromeWithColNumbers',Lb='\n',Mb='debug',Nb='off',Ob='Unexpected exception in debug mode detection, debug mode will be disabled: ',Pb='user.agent',Qb='webkit',Rb='safari',Sb='msie',Tb=11,Ub='ie10',Vb=9,Wb='ie9',Xb=8,Yb='ie8',Zb='gecko',$b='gecko1_8',_b=2,ac=3,bc=4,cc='selectingPermutation',dc='com.typeracer.guest.Guest.devmode.js',ec='false',fc='014774869E9AF721552D0B3894854805',gc='on',hc=':1',ic='3B462584E16136BF4D80BD83D2F0D840',jc='true',kc='60910BF4927E9981AECDCB099B664C6E',lc='71CD44A865B0785720906D9E9F7C9402',mc='D3BC887235CB3D765EAAF7BF9DF7FD4B',nc='FBCB8FD50E1664C35986B0466B16DD1B',oc=':',pc='.cache.js',qc='link',rc='rel',sc='stylesheet',tc='href',uc='loadExternalRefs',vc='TypingLog.css',wc='end',xc='http:',yc='file:',zc='_gwt_dummy_',Ac='__gwtDevModeHook:com.typeracer.guest.Guest',Bc='Ignoring non-whitelisted Dev Mode URL: ',Cc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_typeracer_guest_Guest.__sendStats=r;com_typeracer_guest_Guest.__moduleName=S;com_typeracer_guest_Guest.__errFn=null;com_typeracer_guest_Guest.__moduleBase=U;com_typeracer_guest_Guest.__softPermutationId=V;com_typeracer_guest_Guest.__computePropValue=null;com_typeracer_guest_Guest.__getPropMap=null;com_typeracer_guest_Guest.__installRunAsyncCode=function(){};com_typeracer_guest_Guest.__gwtStartLoadingFragment=function(){return null};com_typeracer_guest_Guest.__gwt_isKnownPropertyValue=function(){return false};com_typeracer_guest_Guest.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};com_typeracer_guest_Guest.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[com_typeracer_guest_Guest.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.id=S;a.style.cssText=Y+Z;a.tabIndex=-1;p.body.appendChild(a);u=a.contentWindow.document;u.open();var b=document.compatMode==$?_:ab;u.write(b+bb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==cb){return typeof p.body!=cb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(p.removeEventListener){p.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(gb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(hb));g=e.createElement(ib);g.language=jb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(ib);g.language=jb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_typeracer_guest_Guest.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;if(com_typeracer_guest_Guest.__errFn){n.onerror=function(){com_typeracer_guest_Guest.__errFn(mb,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
com_typeracer_guest_Guest.__startLoadingFragment=function(a){return D(a)};com_typeracer_guest_Guest.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(ib);d.language=jb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,ab);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=ab}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;com_typeracer_guest_Guest.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return ab}
function h(){var a=p.getElementsByTagName(ib);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return ab}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_typeracer_guest_Guest.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){if(Error&&Error.captureStackTrace){try{null.a()}catch(a){if(a.stack){var b=a.stack.split(Lb);if(b&&(b.length>W&&/:\d+:\d+\)?\s*$/.test(b[W]))){return true}}}}return false};i[Kb]={'false':V,'true':W};j[Mb]=function(){try{var b=null;var c=/[?&]debug=(.*?)(?:&|$)/.exec(location.search);if(c)b=c[W];if(b==null||!__gwt_isKnownPropertyValue(Mb,b)){return Nb}return b}catch(a){alert(Ob+a);return Nb}};i[Mb]={'off':V,'on':W};j[Pb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Qb)!=-1}())return Rb;if(function(){return a.indexOf(Sb)!=-1&&(b>=eb&&b<Tb)}())return Ub;if(function(){return a.indexOf(Sb)!=-1&&(b>=Vb&&b<Tb)}())return Wb;if(function(){return a.indexOf(Sb)!=-1&&(b>=Xb&&b<Tb)}())return Yb;if(function(){return a.indexOf(Zb)!=-1||b>=Tb}())return $b;return ab};i[Pb]={'gecko1_8':V,'ie10':W,'ie8':_b,'ie9':ac,'safari':bc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};com_typeracer_guest_Guest.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};com_typeracer_guest_Guest.__computePropValue=k;o.__gwt_activeModules[S].bindings=com_typeracer_guest_Guest.__getPropMap;r(O,cc);if(q()){return D(dc)}var l;try{h([ec,Nb,$b],fc);h([ec,gc,$b],fc+hc);h([ec,Nb,Wb],ic);h([ec,gc,Wb],ic+hc);h([jc,Nb,Rb],kc);h([jc,gc,Rb],kc+hc);h([ec,Nb,Yb],lc);h([ec,gc,Yb],lc+hc);h([ec,Nb,Ub],mc);h([ec,gc,Ub],mc+hc);h([ec,Nb,Rb],nc);h([ec,gc,Rb],nc+hc);l=f[k(Kb)][k(Mb)][k(Pb)];var m=l.indexOf(oc);if(m!=-1){g=parseInt(l.substring(m+W),eb);l=l.substring(V,m)}}catch(a){}com_typeracer_guest_Guest.__softPermutationId=g;return D(l+pc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(qc);b.setAttribute(rc,sc);b.setAttribute(tc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(uc,P);c(vc);r(uc,wc)}
B();com_typeracer_guest_Guest.__moduleBase=C();t[S].moduleBase=com_typeracer_guest_Guest.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==xc||o.location.protocol==yc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=zc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Ac;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Bc+L)}L=ab}if(L&&!o[K]){o[K]=true;o[K+Cc]=C();var M=p.createElement(ib);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,wc);A(H);return true}
com_typeracer_guest_Guest.succeeded=com_typeracer_guest_Guest();